FROM python:3.10-slim

WORKDIR /app

COPY requirements_backend.txt .

RUN pip install --no-cache-dir torch torchvision  --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir -r requirements_backend.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
